# foundry.toml

[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# ... other config ...

[rpc_endpoints]
celoSepolia = "${CELO_SEPOLIA_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
celoSepolia = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }
baseSepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }